language: node_js
node_js:
  - 10
cache:
  directories:
  - node_modules
before_install:
  - npm install -g @lhci/cli@0.3.x
script:
  - echo $TRAVIS_TAG
  - npm run lint
  - npm run build:prod
  - lhci autorun # run lighthouse CI
deploy:
  target-branch: master
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
addons:
  chrome: stable # make sure you have Chrome available
