language: node_js
node_js:
  - 10
cache:
  directories:
  - node_modules
addons:
  chrome: stable # make sure you have Chrome available
before_install:
  - npm install -g @lhci/cli@0.3.x
script:
  - npm ci
  - npm run lint
  - npm run build:prod
after_success:
  - lhci autorun --assert.preset=lighthouse:recommended
  - lhci autorun --upload.target=temporary-public-storage
deploy:
  target-branch: master
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
