name: Build website on tag

on:
  push:
    tags:
    - '*'

jobs:
  build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [10.x]
      steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
        env:
          CI: true
      - name: Run Linting
        run: npm run lint
        env:
          CI: true
      - name: Build Prod bundle
        run: npm run build:prod
        env:
          CI: true
